# Generated by Django 5.0.4 on 2024-05-17 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('sail_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('owners', models.CharField(max_length=80, null=True)),
                ('helm', models.CharField(max_length=80, null=True)),
                ('flag', models.CharField(blank=True, max_length=80)),
                ('updated_by', models.CharField(max_length=80, null=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalHandicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historical_handicap', models.SmallIntegerField(null=True)),
                ('reason_for_change', models.CharField(max_length=80, null=True)),
                ('amended_by', models.CharField(max_length=80, null=True)),
                ('updated', models.DateField(auto_now=True)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_handicap', to='yachts.yacht')),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Provisional', 'Provisional'), ('Ratified', 'Ratified'), ('None', 'None')], default='Provisional', max_length=12)),
                ('current_handicap', models.SmallIntegerField()),
                ('reason_for_change', models.CharField(max_length=80)),
                ('amended_by', models.CharField(max_length=80)),
                ('updated', models.DateField(auto_now=True)),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yachts.yacht')),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins_this_year', models.SmallIntegerField(verbose_name='wins')),
                ('places_this_year', models.SmallIntegerField(verbose_name='places')),
                ('races_this_year', models.SmallIntegerField(verbose_name='no races this year')),
                ('average_hCap_change_to_win', models.SmallIntegerField(verbose_name='ave hcw')),
                ('standard_deviation_hCap_change_to_win', models.SmallIntegerField(verbose_name='std dev hcw')),
                ('average_position', models.SmallIntegerField(verbose_name='average position')),
                ('yacht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='yachts.yacht')),
            ],
        ),
    ]
